### ISSUE TITLE
unable to add add-in

### ISSUE THREAD

**Issue by hweisenborn** [nicogis/RemoveClassExtension#1]
I'm a front-end user with little or no programming experience, so please forgive me if this a no-brainer.  For whatever reason, I can't get this add-in onto ArcGIS 10.4.  It doesn't seem to have any component library file types that the add-in manager recognizes (.dll, .esriAddIn, .tlb).  There is an .esriaddinx file in the folder, but add-in manager does not recognize it.  Removing the ‘x’ doesn’t work either.  Nor does copying the github add-in folder into my default “AddIns” folder for Desktop10.4.  Any assistance would be greatly appreciated!

**Comment by nicogis** [comment]
If you haven't got Visual Studio 2015 with sdk arcobjects to compile source code, you can download addin file here: https://github.com/nicogis/RemoveClassExtension/releases 
The addin file is StudioAT.ArcGIS.ArcCatalog.AddIn.RemoveClassExtension.esriAddIn

**Comment by hweisenborn** [comment]
Whoops, overlooked that.  Thanks for the quick response!
- Harry 
  
  On Friday, August 12, 2016 12:32 PM, Domenico Ciavarella notifications@github.com wrote:
  
  If you haven't got Visual Studio 2015 with sdk arcobjects to compile source code, you can downloads addin file here: https://github.com/nicogis/RemoveClassExtension/releases 
  The addin file is StudioAT.ArcGIS.ArcCatalog.AddIn.RemoveClassExtension.esriAddIn—
