### ISSUE TITLE
Tool buttons are disabled

### ISSUE THREAD

**Issue by cgis12** [nicogis/RemoveClassExtension#2]
Hi -
I installed the addin and added the buttons to an existing menu, but when I go to the feature class that has the object extensions and receive the error, after clicking OK the buttons are still disabled. How can I enable them & use them? I'm currently on 10.4 w/no sp/patches. Thanks!
![image](https://cloud.githubusercontent.com/assets/23122749/19809736/92042954-9cf8-11e6-98fe-dcc4de96dfaa.png)

**Comment by nicogis** [comment]
Select a gdb in catalog tree and in tab Contents select the feature class 
![image](https://cloud.githubusercontent.com/assets/5425886/19810899/7ec99f2c-9d2f-11e6-9bd2-bcbe13ac201c.png)

**Comment by cgis12** [comment]
Thanks, your tool works perfectly!!
