### ISSUE TITLE
Issue ' Not found component register so I don't see the UID.......'

### ISSUE THREAD

**Issue by tshewring-he** [nicogis/RemoveClassExtension#4]
Hi,
I have installed the AddIn from https://github.com/nicogis/RemoveClassExtension/releases
I am using ArcCatalog / ArcMap 10.8.2
I have added the tools to a new toolbar
I create a direct connection into an ArcSDE (10.8.2) Oracle19C Geodatabase
I have a number of Featureclasses in the database with Featureclass extensions
When I select a featureclass and click on the 'Remove Class Extension' or 'Remove Instance Class' button I get the message 'Not found component register so I don't see the UID:do I have to remove class extension? Are you sure?'
Do you know why I am getting this message?
Are the tools compatible with 10.8.2?
Thanks

**Comment by nicogis** [comment]
Yes, because the feature class selected has an uid (class extension/Instance class) but in your machine you haven't registered dll of class (uid) so I ask you confirm if I clear this guid in feature class. So if you need use feature class because you haven't dll the message is ok
